name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, scan, and push Docker image
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache 
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache

      - name: Scan Docker image for vulnerabilities
        id: scan
        uses: docker/scout-action@v1
        with:
          image: ${{ steps.build.outputs.image }}

      - name: Fail if vulnerabilities found
        if: steps.scan.outputs.vulnerability-severity != 'low'
        run: exit 1

      - name: Push Docker image to DockerHub
        if: steps.scan.outputs.vulnerability-severity == 'low'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache 
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/example:cache

      - name: Login to GitHub Container Registry
        if: steps.scan.outputs.vulnerability-severity == 'low'
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        if: steps.scan.outputs.vulnerability-severity == 'low'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/example:${{ steps.meta.outputs.tags }}

